/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BpProject2;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;

/**
 *
 * @author fbali
 */
public class Ali_Yilmaz_2121221031_bp2_p2_Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Ali_Yilmaz_2121221031_bp2_p2_Main() {

        initComponents();
        this.setTitle("Ana Ekran");
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btn_EkleSil = new javax.swing.JButton();
        btn_AraGuncelle = new javax.swing.JButton();
        btn_TalepOlustur = new javax.swing.JButton();
        btn_SirketHk = new javax.swing.JButton();
        Area_EkleSil = new javax.swing.JLabel();
        lbl_AraGuncelle = new javax.swing.JLabel();
        lbl_TalepOIustur = new javax.swing.JLabel();
        lbl_ŞirketHk = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Item_EkleSil = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        Item_AraGuncelle = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        Item_TalepOlustur = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        Item_SirketHk = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel2.setBackground(new java.awt.Color(59, 17, 9));

        btn_EkleSil.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btn_EkleSil.setForeground(new java.awt.Color(255, 0, 0));
        btn_EkleSil.setText("Malzeme Ekle Sil");
        btn_EkleSil.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btn_EkleSilFocusGained(evt);
            }
        });
        btn_EkleSil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_EkleSilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_EkleSilMouseExited(evt);
            }
        });
        btn_EkleSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EkleSilActionPerformed(evt);
            }
        });

        btn_AraGuncelle.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btn_AraGuncelle.setForeground(new java.awt.Color(255, 51, 0));
        btn_AraGuncelle.setText("Malzeme Ara Güncelle");
        btn_AraGuncelle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_AraGuncelleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_AraGuncelleMouseExited(evt);
            }
        });
        btn_AraGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AraGuncelleActionPerformed(evt);
            }
        });

        btn_TalepOlustur.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btn_TalepOlustur.setForeground(new java.awt.Color(255, 51, 0));
        btn_TalepOlustur.setText("Ürün Talebi Oluştur Sil");
        btn_TalepOlustur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_TalepOlusturMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_TalepOlusturMouseExited(evt);
            }
        });
        btn_TalepOlustur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TalepOlusturActionPerformed(evt);
            }
        });

        btn_SirketHk.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btn_SirketHk.setForeground(new java.awt.Color(204, 51, 0));
        btn_SirketHk.setText("Şirket Hakkında");
        btn_SirketHk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_SirketHkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_SirketHkMouseExited(evt);
            }
        });
        btn_SirketHk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SirketHkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_EkleSil, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                    .addComponent(btn_TalepOlustur, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                    .addComponent(btn_AraGuncelle, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                    .addComponent(btn_SirketHk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btn_EkleSil, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btn_AraGuncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btn_TalepOlustur, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btn_SirketHk, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        Area_EkleSil.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        Area_EkleSil.setForeground(new java.awt.Color(0, 0, 0));
        Area_EkleSil.setText("--> Burada malzeme ekleme ve silme işlemleri yapabilirsiniz . Silme için Admin olmalısınız.");

        lbl_AraGuncelle.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lbl_AraGuncelle.setForeground(new java.awt.Color(0, 0, 0));
        lbl_AraGuncelle.setText("--> Burada Malzemeleri Listelerden görebilir ve güncelleyebilirsiniz. Ayriyeten özel arama yapabilirsiniz.");

        lbl_TalepOIustur.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lbl_TalepOIustur.setForeground(new java.awt.Color(0, 0, 0));
        lbl_TalepOIustur.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_TalepOIustur.setText("--> Burada Ürün Talep Ekleme,Silme,Arama ve Güncelleme yapabilirsiniz. Silme için Admin olmalısınız.");
        lbl_TalepOIustur.setAlignmentY(0.0F);

        lbl_ŞirketHk.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lbl_ŞirketHk.setForeground(new java.awt.Color(0, 0, 0));
        lbl_ŞirketHk.setText("--> Burada Şirketimiz Hakkında bilgilendirmeleri ve gizlilik politikalarını bulabilirsiniz.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Area_EkleSil, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lbl_AraGuncelle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_TalepOIustur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lbl_ŞirketHk, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(Area_EkleSil)
                .addGap(64, 64, 64)
                .addComponent(lbl_AraGuncelle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_TalepOIustur)
                .addGap(61, 61, 61)
                .addComponent(lbl_ŞirketHk)
                .addGap(35, 35, 35))
        );

        getContentPane().add(jPanel1);

        jMenuBar1.setBackground(new java.awt.Color(0, 255, 153));
        jMenuBar1.setForeground(new java.awt.Color(255, 204, 204));

        jMenu1.setText("Malzeme Ekle/Sil");

        Item_EkleSil.setText("Ekle/Sil");
        Item_EkleSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_EkleSilActionPerformed(evt);
            }
        });
        jMenu1.add(Item_EkleSil);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Malzeme Ara/Guncelle");
        jMenu2.add(jSeparator2);

        Item_AraGuncelle.setText("Ara/Guncelle");
        Item_AraGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_AraGuncelleActionPerformed(evt);
            }
        });
        jMenu2.add(Item_AraGuncelle);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Talep Oluştur");

        Item_TalepOlustur.setText("Talep Oluştur");
        Item_TalepOlustur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_TalepOlusturActionPerformed(evt);
            }
        });
        jMenu3.add(Item_TalepOlustur);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Şirket Hk.");

        Item_SirketHk.setText("Şirket Hakkında");
        Item_SirketHk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_SirketHkActionPerformed(evt);
            }
        });
        jMenu4.add(Item_SirketHk);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Item_EkleSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_EkleSilActionPerformed
        // TODO add your handling code here:
        MalzemeEkleSilCagir();

    }//GEN-LAST:event_Item_EkleSilActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
      //    //her bireylem için popup oluşturma
        if (evt.getButton() == MouseEvent.BUTTON3) {
        JPopupMenu popupMenu = new JPopupMenu();

        JMenuItem item1 = new JMenuItem("Ekle/Sil");
        item1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                MalzemeEkleSilCagir();
            }
        });
        popupMenu.add(item1);

        JMenuItem item2 = new JMenuItem("Ara/Guncelle");
        item2.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                MalzemeAraGuncelleCagir();
            }
        });
        popupMenu.add(item2);

        JMenuItem item3 = new JMenuItem("Talep Oluşturma");
        item3.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                TalepOlusturmaCagir();
            }
        });
        popupMenu.add(item3);

        JMenuItem item4 = new JMenuItem("Şirket Hakkında");
        item4.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                SirketHakkindaCagir();
            }
        });
        popupMenu.add(item4);

        // Pop-up menüyü göstermek için gerekli kod
        popupMenu.show(evt.getComponent(), evt.getX(), evt.getY());
    }
    }//GEN-LAST:event_formMouseClicked

    private void Item_AraGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_AraGuncelleActionPerformed
        // TODO add your handling code here:
        MalzemeAraGuncelleCagir();
    }//GEN-LAST:event_Item_AraGuncelleActionPerformed

    private void MalzemeEkleSilCagir() {
        Ali_Yilmaz_2121221031_bp2_p2_MalzemeEkleSil EkleSil = new Ali_Yilmaz_2121221031_bp2_p2_MalzemeEkleSil();
        EkleSil.setVisible(true);
        dispose();

    }

    private void MalzemeAraGuncelleCagir() {
        
        Ali_Yilmaz_2121221031_bp2_p2_MalzemeAraGuncelle araguncelle = new Ali_Yilmaz_2121221031_bp2_p2_MalzemeAraGuncelle();
        araguncelle.setVisible(true);
        dispose();
    }

    private void TalepOlusturmaCagir() {
        Ali_Yilmaz_2121221031_bp2_p2_UrunTalebiOlustur talep = new Ali_Yilmaz_2121221031_bp2_p2_UrunTalebiOlustur();
        talep.setVisible(true);
        this.dispose();

    }
    private void SirketHakkindaCagir(){
    Ali_Yilmaz_2121221031_bp2_p2_SirketHk sirket=new Ali_Yilmaz_2121221031_bp2_p2_SirketHk();
        sirket.setVisible(true);
        this.dispose();
    }
    private void btn_EkleSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EkleSilActionPerformed
        // TODO add your handling code here:
        MalzemeEkleSilCagir();
    }//GEN-LAST:event_btn_EkleSilActionPerformed

    private void btn_AraGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AraGuncelleActionPerformed
        // TODO add your handling code here:
        MalzemeAraGuncelleCagir();
    }//GEN-LAST:event_btn_AraGuncelleActionPerformed

    private void btn_EkleSilFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btn_EkleSilFocusGained
        // TODO add your handling code here:
        //  Area_EkleSil.setVisible(true);
    }//GEN-LAST:event_btn_EkleSilFocusGained

    private void btn_EkleSilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EkleSilMouseEntered
        // TODO add your handling code here:
        Area_EkleSil.setVisible(true);
    }//GEN-LAST:event_btn_EkleSilMouseEntered

    private void btn_EkleSilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_EkleSilMouseExited
        // TODO add your handling code here:
        Area_EkleSil.setVisible(false);
    }//GEN-LAST:event_btn_EkleSilMouseExited

    private void btn_TalepOlusturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TalepOlusturActionPerformed
        // TODO add your handling code here:
        TalepOlusturmaCagir();
    }//GEN-LAST:event_btn_TalepOlusturActionPerformed

    private void Item_TalepOlusturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_TalepOlusturActionPerformed
        // TODO add your handling code here:
        TalepOlusturmaCagir();

    }//GEN-LAST:event_Item_TalepOlusturActionPerformed

    private void btn_AraGuncelleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AraGuncelleMouseEntered
        // TODO add your handling code here:
        lbl_AraGuncelle.setVisible(true);
    }//GEN-LAST:event_btn_AraGuncelleMouseEntered

    private void btn_AraGuncelleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AraGuncelleMouseExited
        // TODO add your handling code here:
               lbl_AraGuncelle.setVisible(false);
    }//GEN-LAST:event_btn_AraGuncelleMouseExited

    private void btn_TalepOlusturMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_TalepOlusturMouseEntered
        // TODO add your handling code here:
        lbl_TalepOIustur.setVisible(true);
    }//GEN-LAST:event_btn_TalepOlusturMouseEntered

    private void btn_TalepOlusturMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_TalepOlusturMouseExited
        // TODO add your handling code here:
                lbl_TalepOIustur.setVisible(false);
    }//GEN-LAST:event_btn_TalepOlusturMouseExited

    private void btn_SirketHkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SirketHkMouseEntered
        // TODO add your handling code here:
        lbl_ŞirketHk.setVisible(true);
    }//GEN-LAST:event_btn_SirketHkMouseEntered

    private void btn_SirketHkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SirketHkMouseExited
        // TODO add your handling code here:
              lbl_ŞirketHk.setVisible(false);
    }//GEN-LAST:event_btn_SirketHkMouseExited

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        Area_EkleSil.setVisible(false);
        lbl_AraGuncelle.setVisible(false);
        lbl_TalepOIustur.setVisible(false);
        lbl_ŞirketHk.setVisible(false);
        
    }//GEN-LAST:event_formWindowOpened

    private void btn_SirketHkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SirketHkActionPerformed
SirketHakkindaCagir();
    }//GEN-LAST:event_btn_SirketHkActionPerformed

    private void Item_SirketHkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_SirketHkActionPerformed
        // TODO add your handling code here:
        SirketHakkindaCagir();
    }//GEN-LAST:event_Item_SirketHkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ali_Yilmaz_2121221031_bp2_p2_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ali_Yilmaz_2121221031_bp2_p2_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ali_Yilmaz_2121221031_bp2_p2_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ali_Yilmaz_2121221031_bp2_p2_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ali_Yilmaz_2121221031_bp2_p2_Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Area_EkleSil;
    private javax.swing.JMenuItem Item_AraGuncelle;
    private javax.swing.JMenuItem Item_EkleSil;
    private javax.swing.JMenuItem Item_SirketHk;
    private javax.swing.JMenuItem Item_TalepOlustur;
    private javax.swing.JButton btn_AraGuncelle;
    private javax.swing.JButton btn_EkleSil;
    private javax.swing.JButton btn_SirketHk;
    private javax.swing.JButton btn_TalepOlustur;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JLabel lbl_AraGuncelle;
    private javax.swing.JLabel lbl_TalepOIustur;
    private javax.swing.JLabel lbl_ŞirketHk;
    // End of variables declaration//GEN-END:variables
}
