/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BpProject2;

import java.sql.Date;
import java.sql.SQLIntegrityConstraintViolationException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fbali
 */
public class Ali_Yilmaz_2121221031_bp2_p2_MalzemeEkleSil extends javax.swing.JFrame {

    /**
     * Creates new form MalzemeEkle
     */
    public Ali_Yilmaz_2121221031_bp2_p2_MalzemeEkleSil() {
        initComponents();
     this.setTitle("Malzeme Ekle Sil");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnl_Ekle = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_MalzemeTedarikci = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtArea_MalzemeAciklamasi = new javax.swing.JTextArea();
        btn_ekle = new javax.swing.JButton();
        cmb_MalzemeKategorisi = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txt_Id = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_malzemeAdi = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_MalzemeStok = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_MalzemeSkt = new com.toedter.calendar.JDateChooser();
        pnl_Sil = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_Sil = new javax.swing.JTable();
        btn_Sil = new javax.swing.JButton();
        txt_Tara = new javax.swing.JTextField();
        btn_Tara = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });
        jTabbedPane1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTabbedPane1FocusGained(evt);
            }
        });
        jTabbedPane1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTabbedPane1KeyPressed(evt);
            }
        });

        pnl_Ekle.setLayout(new javax.swing.BoxLayout(pnl_Ekle, javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Malzeme Ekleme", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Malzeme Tedarikçisi");

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Malzeme Açıklaması");

        txtArea_MalzemeAciklamasi.setColumns(20);
        txtArea_MalzemeAciklamasi.setRows(5);
        jScrollPane2.setViewportView(txtArea_MalzemeAciklamasi);

        btn_ekle.setBackground(new java.awt.Color(0, 153, 153));
        btn_ekle.setText("EKLE");
        btn_ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ekleActionPerformed(evt);
            }
        });

        cmb_MalzemeKategorisi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kimyasallar", "Cam Eşyalar", "Metal Eşyalar", "Plastik Eşyalar", "Ölçüm Cihazları", "Biyolojik Malzemeler", "Elektrikli Malzemeler", "Optik Malzemeler" }));

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Malzeme kodu");

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Malzeme  Adı");

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Malzeme Kategorisi");

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Malzeme Stok");

        jLabel14.setBackground(new java.awt.Color(0, 0, 0));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Malzeme skt");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(89, 89, 89)
                        .addComponent(btn_ekle, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel11)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_MalzemeTedarikci, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12)
                                .addComponent(jLabel14)
                                .addComponent(jLabel13))
                            .addGap(55, 55, 55)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_Id, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                                .addComponent(txt_MalzemeStok)
                                .addComponent(cmb_MalzemeKategorisi, 0, 234, Short.MAX_VALUE)
                                .addComponent(txt_malzemeAdi, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                                .addComponent(txt_MalzemeSkt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(80, 346, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txt_malzemeAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cmb_MalzemeKategorisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txt_MalzemeStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_MalzemeSkt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_MalzemeTedarikci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49)
                .addComponent(btn_ekle)
                .addGap(33, 33, 33))
        );

        pnl_Ekle.add(jPanel1);

        jTabbedPane1.addTab("Malzeme Ekle", pnl_Ekle);

        pnl_Sil.setLayout(new javax.swing.BoxLayout(pnl_Sil, javax.swing.BoxLayout.LINE_AXIS));

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Malzeme Silme", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        table_Sil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Malzeme Kodu", "Malzeme Adı", "Malzeme Kategorisi", "Malzeme Stok", "Malzeme Tedarikçi"
            }
        ));
        jScrollPane1.setViewportView(table_Sil);

        btn_Sil.setText("Veriyi Sil");
        btn_Sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SilActionPerformed(evt);
            }
        });

        btn_Tara.setText("Veriyi Bul");
        btn_Tara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TaraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_Tara, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(txt_Tara)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(btn_Sil, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(txt_Tara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Tara)))
                .addGap(32, 32, 32)
                .addComponent(btn_Sil, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pnl_Sil.add(jPanel2);

        jTabbedPane1.addTab("Malzeme Sil", pnl_Sil);

        getContentPane().add(jTabbedPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ekleActionPerformed
        Ali_Yilmaz_2121221031_bp2_p2_Malzemeler malzeme = new Ali_Yilmaz_2121221031_bp2_p2_Malzemeler();
        // JDateChooser'dan tarihi alın
        
        java.util.Date selectedDate = txt_MalzemeSkt.getDate();
        if(selectedDate!=null){
        // Tarih formatını belirleyin
        java.text.SimpleDateFormat dateFormat = new java.text.SimpleDateFormat("dd/MM/yyyy");

// Seçilen tarihi istediğiniz formatta bir metin olarak alın
        String formattedDate = dateFormat.format(selectedDate);

// Elde edilen metni kullanabilirsiniz
        malzeme.malzeme_skt = formattedDate;
        }else {

    malzeme.malzeme_skt = ""; // veya talep.TalepTarihi = null;
    JOptionPane.showMessageDialog(this, "Geçerli bir tarih seçiniz.", "Hata", JOptionPane.ERROR_MESSAGE);
}



        String idText = txt_Id.getText();
        malzeme.malzeme_adi = txt_malzemeAdi.getText();
        malzeme.malzeme_kategorisi = cmb_MalzemeKategorisi.getSelectedItem().toString();
        malzeme.malzeme_Stok = txt_MalzemeStok.getText();
//malzeme.malzeme_skt = txt_MalzemeSkt.getDate().toString();
        malzeme.malzeme_tedarikci = txt_MalzemeTedarikci.getText();
        malzeme.malzeme_aciklama = txtArea_MalzemeAciklamasi.getText();

        try {
            // regex ve boş olma sorguları
            if (!isValidId(idText)) {
                throw new IllegalArgumentException("Geçersiz Malzeme ID formatı");
            }
            malzeme.id = Integer.parseInt(idText);
            if (idText.isEmpty()) {
                throw new IllegalArgumentException("Malzeme ID alanı boş bırakılamaz");
            }

            if (!isValidMalzemeAdi(malzeme.malzeme_adi)) {
                throw new IllegalArgumentException("Geçersiz malzeme adı formatı");
            }
     
                if (selectedDate == null) {
                    throw new IllegalArgumentException("Malzeme Skt alanı boş bırakılamaz");
                }

            if (malzeme.malzeme_adi.isEmpty()) {
                throw new IllegalArgumentException("Malzeme adı alanı boş bırakılamaz");
            }

            if (malzeme.malzeme_Stok.isEmpty()) {
                throw new IllegalArgumentException("Stok alanı boş bırakılamaz");
            }

            if (malzeme.malzeme_tedarikci.isEmpty()) {
                throw new IllegalArgumentException("Tedarikçi alanı boş bırakılamaz");
            }

    

           
                if (Ali_Yilmaz_2121221031_bp2_p2_MalzemeDB.AddMaterial(malzeme)) {
                    JOptionPane.showMessageDialog(this, "Malzemeler Veri Tabanına Eklendi");
                    TabloSifirlama();
                } else {
                    JOptionPane.showMessageDialog(this, "Veri Tabanına Ekleme Başarısız");
       
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        
        /*
         // Diğer giriş kontrollerini ekleyin..
            String UserId = Ali_Yilmaz_2121221031_bp2_p2_GirisEkrani.UserId;
            String sifre = Ali_Yilmaz_2121221031_bp2_p2_GirisEkrani.Password;

            String position = Ali_Yilmaz_2121221031_bp2_p2_MalzemeDB.getUserPosition(UserId, sifre);
            if (position != null && position.equals("Admin")) {
                if (Ali_Yilmaz_2121221031_bp2_p2_MalzemeDB.AddMaterial(malzeme)) {
                    JOptionPane.showMessageDialog(this, "Ali_Yilmaz_2121221031_bp2_p2_Malzemeler Veri Tabanına Eklendi");
                    TabloSifirlama();
                } else {
                    JOptionPane.showMessageDialog(this, "Veri Tabanına Ekleme Başarısız");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Malzeme eklemek için Admin olmanız gerekli");
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

        */


    }//GEN-LAST:event_btn_ekleActionPerformed

    private void TabloSifirlama() {
        this.txt_Id.setText("");
        this.txt_malzemeAdi.setText("");
        this.txt_MalzemeStok.setText("");
        txt_MalzemeSkt.setDate(null);

        this.txt_MalzemeTedarikci.setText("");
        this.txtArea_MalzemeAciklamasi.setText("");

    }

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged

        // TODO add your handling code here:

    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void jTabbedPane1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTabbedPane1KeyPressed

    }//GEN-LAST:event_jTabbedPane1KeyPressed

    private void jTabbedPane1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTabbedPane1FocusGained
        // TODO add your handling code here:
        int selectedTabIndex = jTabbedPane1.getSelectedIndex();

        // İlgili sekme görüntülendiğinde yapılacak işlemler
        if (selectedTabIndex == 0) {
            updateTable(); // Verileri tabloya çeken metodunuzu buraya çağırın
        }
    }//GEN-LAST:event_jTabbedPane1FocusGained

    private void btn_SilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SilActionPerformed

        String kullaniciAdi = Ali_Yilmaz_2121221031_bp2_p2_GirisEkrani.UserId;
        String sifre = Ali_Yilmaz_2121221031_bp2_p2_GirisEkrani.Password;
        String position = Ali_Yilmaz_2121221031_bp2_p2_MalzemeDB.getUserPosition(kullaniciAdi, sifre);

        if (position != null) {
            // Kullanıcı doğrulandı, işleme devam et
            if (position.equals("Admin")) {
                int choice = JOptionPane.showConfirmDialog(this, "Gerçekten silmek istiyor musunuz? Bu işlem geri alınamaz.", "Malzeme Silme", JOptionPane.YES_NO_OPTION);
                if (choice == JOptionPane.YES_OPTION) {
                    int selectedRow = table_Sil.getSelectedRow();

                    // Satırın verilerini al
                    int id = Integer.parseInt(table_Sil.getValueAt(selectedRow, 0).toString());
                    // Diğer verileri de ihtiyaca göre al

                    // Veriyi sil
                    boolean isDeleted = Ali_Yilmaz_2121221031_bp2_p2_MalzemeDB.DeleteById(id);
                    if (isDeleted) {
                        // Veri silme işlemi başarılıysa
                        JOptionPane.showMessageDialog(this, "Veri başarıyla silindi.");

                        // Tabloyu güncelle
                        updateTable();
                    } else {
                        // Veri silme işlemi başarısızsa
                        JOptionPane.showMessageDialog(this, "Veri silme işlemi başarısız.");
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Silmek için Admin olmanız gerekli", "Silme işlemi", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Kullanıcı adı veya şifre hatalı", "Hatalı Giriş", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btn_SilActionPerformed

    private void btn_TaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TaraActionPerformed
        // TODO add your handling code here:
        String search = txt_Tara.getText();
        DefaultTableModel model = (DefaultTableModel) table_Sil.getModel();
        ArrayList<Ali_Yilmaz_2121221031_bp2_p2_Malzemeler> mlist = Ali_Yilmaz_2121221031_bp2_p2_MalzemeDB.searchByNameOrId(search);
        model.setRowCount(0);

        // Tablo modeline verileri eklemeden önce tablonun içeriğini temizleyin
         
        for (Ali_Yilmaz_2121221031_bp2_p2_Malzemeler nm1 : mlist) {
            model.addRow(new Object[]{nm1.id, nm1.malzeme_adi, nm1.malzeme_kategorisi, nm1.malzeme_Stok, nm1.malzeme_tedarikci});
        }
    }//GEN-LAST:event_btn_TaraActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        Ali_Yilmaz_2121221031_bp2_p2_Main main = new Ali_Yilmaz_2121221031_bp2_p2_Main();
        main.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void updateTable() {
        DefaultTableModel model = (DefaultTableModel) table_Sil.getModel();
        model.setRowCount(0); // Tabloyu temizle

        // Veritabanından verileri çekme işlemleri
        ArrayList<Ali_Yilmaz_2121221031_bp2_p2_Malzemeler> malzemeler = Ali_Yilmaz_2121221031_bp2_p2_MalzemeDB.getMaterials();

        // Verileri tabloya ekleme
        for (Ali_Yilmaz_2121221031_bp2_p2_Malzemeler malzeme : malzemeler) {
            Object[] row = {malzeme.id, malzeme.malzeme_adi, malzeme.malzeme_kategorisi, malzeme.malzeme_Stok, malzeme.malzeme_tedarikci,};
            model.addRow(row);
        }
    }

    // ID için geçerlilik kontrolü
    private boolean isValidId(String idText) {
        String regex = "^[1-9]\\d*$"; // 0'dan farklı pozitif tam sayılar
        return idText.matches(regex);
    }

// Malzeme adı için geçerlilik kontrolü
    private boolean isValidMalzemeAdi(String malzemeAdi) {
        String regex = "^[A-Za-z\\s]+$"; // Sadece harf ve boşluk içeren metin
        return malzemeAdi.matches(regex) && !malzemeAdi.trim().isEmpty();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ali_Yilmaz_2121221031_bp2_p2_MalzemeEkleSil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ali_Yilmaz_2121221031_bp2_p2_MalzemeEkleSil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ali_Yilmaz_2121221031_bp2_p2_MalzemeEkleSil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ali_Yilmaz_2121221031_bp2_p2_MalzemeEkleSil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ali_Yilmaz_2121221031_bp2_p2_MalzemeEkleSil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Sil;
    private javax.swing.JButton btn_Tara;
    private javax.swing.JButton btn_ekle;
    private javax.swing.JComboBox<String> cmb_MalzemeKategorisi;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel pnl_Ekle;
    private javax.swing.JPanel pnl_Sil;
    private javax.swing.JTable table_Sil;
    private javax.swing.JTextArea txtArea_MalzemeAciklamasi;
    private javax.swing.JTextField txt_Id;
    private com.toedter.calendar.JDateChooser txt_MalzemeSkt;
    private javax.swing.JTextField txt_MalzemeStok;
    private javax.swing.JTextField txt_MalzemeTedarikci;
    private javax.swing.JTextField txt_Tara;
    private javax.swing.JTextField txt_malzemeAdi;
    // End of variables declaration//GEN-END:variables
}
