/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BpProject2;

import java.awt.List;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fbali
 */
public class Ali_Yilmaz_2121221031_bp2_p2_MalzemeAraGuncelle extends javax.swing.JFrame {

    /**
     * Creates new form MalzemeAraGuncelle
     */
    public Ali_Yilmaz_2121221031_bp2_p2_MalzemeAraGuncelle() {
        initComponents();
        this.setTitle("Malzeme Ara Güncelle");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_MalzemeTedarikciGuncelleme = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtArea_MalzemeAciklamasiGuncelleme = new javax.swing.JTextArea();
        btn_Guncelle = new javax.swing.JButton();
        cmb_MalzemeKategorisiGuncelleme = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txt_IdGuncelleme = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_malzemeAdiGuncelleme = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_MalzemeStokGuncelleme = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Guncelle = new javax.swing.JTable();
        btn_GuncelleTara = new javax.swing.JButton();
        txt_GuncelleTara = new javax.swing.JTextField();
        txt_MalzemeSktGuncelleme = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Malzeme Güncelleme", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        jPanel2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel2FocusGained(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Malzeme Tedarikçisi");

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Malzeme Açıklaması");

        txtArea_MalzemeAciklamasiGuncelleme.setColumns(20);
        txtArea_MalzemeAciklamasiGuncelleme.setRows(5);
        jScrollPane2.setViewportView(txtArea_MalzemeAciklamasiGuncelleme);

        btn_Guncelle.setBackground(new java.awt.Color(0, 153, 153));
        btn_Guncelle.setText("GÜNCELLE");
        btn_Guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GuncelleActionPerformed(evt);
            }
        });

        cmb_MalzemeKategorisiGuncelleme.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kimyasallar", "Cam Eşyalar", "Metal Eşyalar", "Plastik Eşyalar", "Ölçüm Cihazları", "Biyolojik Malzemeler", "Elektrikli Malzemeler", "Optik Malzemeler" }));

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Malzeme kodu");

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Malzeme  Adı");

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Malzeme Kategorisi");

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Malzeme Stok");

        jLabel14.setBackground(new java.awt.Color(0, 0, 0));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Malzeme skt");

        tbl_Guncelle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Malzeme Adı", "Malzeme Kategori", "Malzeme Stok", "Malzeme Skt", "Malzeme Tedarikçi", "Malzeme Açıklama"
            }
        ));
        jScrollPane1.setViewportView(tbl_Guncelle);

        btn_GuncelleTara.setText("Veriyi Tara");
        btn_GuncelleTara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GuncelleTaraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addGap(89, 89, 89)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_Guncelle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_MalzemeTedarikciGuncelleme, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel14)
                                        .addComponent(jLabel13))
                                    .addGap(55, 55, 55)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txt_IdGuncelleme, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                                        .addComponent(txt_MalzemeStokGuncelleme)
                                        .addComponent(cmb_MalzemeKategorisiGuncelleme, 0, 234, Short.MAX_VALUE)
                                        .addComponent(txt_malzemeAdiGuncelleme, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                                        .addComponent(txt_MalzemeSktGuncelleme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(btn_GuncelleTara)
                        .addGap(42, 42, 42)
                        .addComponent(txt_GuncelleTara, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 807, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_GuncelleTara, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_GuncelleTara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_IdGuncelleme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txt_malzemeAdiGuncelleme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cmb_MalzemeKategorisiGuncelleme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txt_MalzemeStokGuncelleme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(txt_MalzemeSktGuncelleme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_MalzemeTedarikciGuncelleme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_Guncelle)
                .addGap(33, 33, 33))
        );

        jPanel1.add(jPanel2);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_GuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GuncelleActionPerformed
        // Tablodan seçilen satırın indeksini alın
        int selectedRowIndex = tbl_Guncelle.getSelectedRow();

        // Seçilen bir satır varsa devam edin
        if (selectedRowIndex != -1) {
            Ali_Yilmaz_2121221031_bp2_p2_Malzemeler updateMalzeme = new Ali_Yilmaz_2121221031_bp2_p2_Malzemeler();

            try {
                // Seçilen satırdaki ID değerini alın
                int idText = Integer.parseInt(txt_IdGuncelleme.getText());

                // Tablodan ilgili veriyi alın
                Ali_Yilmaz_2121221031_bp2_p2_Malzemeler existingMalzeme = Ali_Yilmaz_2121221031_bp2_p2_MalzemeDB.getMaterialById(idText);

                if (existingMalzeme == null) {
                    throw new IllegalArgumentException("Güncelleme yapılacak Malzeme bulunamadı");
                }

                // Verinin ID değerini kontrol edin
                if (idText != existingMalzeme.getId()) {
                    throw new IllegalArgumentException("Güncelleme yapılacak Malzeme ID'si eşleşmiyor");
                }

                String malzeme_adi = txt_malzemeAdiGuncelleme.getText();
                String malzeme_kategorisi = cmb_MalzemeKategorisiGuncelleme.getSelectedItem().toString();
                String malzeme_Stok = txt_MalzemeStokGuncelleme.getText();
                java.util.Date selectedDate = txt_MalzemeSktGuncelleme.getDate();

// Tarih formatını belirleyin
                java.text.SimpleDateFormat dateFormat = new java.text.SimpleDateFormat("dd/MM/yyyy");

// Seçilen tarihi istediğiniz formatta bir metin olarak alın
                String formattedDate = dateFormat.format(selectedDate);


                String malzeme_tedarikci = txt_MalzemeTedarikciGuncelleme.getText();
                String malzeme_aciklama = txtArea_MalzemeAciklamasiGuncelleme.getText();

                if (!isValidId(idText)) {
                    throw new IllegalArgumentException("Geçersiz Malzeme ID formatı");
                }

                if (malzeme_adi.isEmpty()) {
                    throw new IllegalArgumentException("Malzeme adı alanı boş bırakılamaz");
                }

                if (!isValidMalzemeAdi(malzeme_adi)) {
                    throw new IllegalArgumentException("Geçersiz malzeme adı formatı");
                }

                if (malzeme_Stok.isEmpty()) {
                    throw new IllegalArgumentException("Stok alanı boş bırakılamaz");
                }

                if (malzeme_tedarikci.isEmpty()) {
                    throw new IllegalArgumentException("Tedarikçi alanı boş bırakılamaz");
                }

                updateMalzeme.setId(idText);
                updateMalzeme.setMalzeme_adi(malzeme_adi);
                updateMalzeme.setMalzeme_kategorisi(malzeme_kategorisi);
                updateMalzeme.setMalzeme_Stok(malzeme_Stok);
                updateMalzeme.setMalzeme_skt(formattedDate);
                updateMalzeme.setMalzeme_tedarikci(malzeme_tedarikci);
                updateMalzeme.setMalzeme_aciklama(malzeme_aciklama);

                if (Ali_Yilmaz_2121221031_bp2_p2_MalzemeDB.UpdateMaterial(updateMalzeme)) {
                    JOptionPane.showMessageDialog(this, "Malzeme Veri Tabanında Güncellendi");
                    TabloSifirlama();
                } else {
                    JOptionPane.showMessageDialog(this, "Veri Tabanında Güncelleme Başarısız");
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Geçersiz ID formatı");
            } catch (IllegalArgumentException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Tablodan güncellenecek bir değer seçin!");
        }
    }//GEN-LAST:event_btn_GuncelleActionPerformed

    private void TabloSifirlama() {
        //tablo sıfırlama
        this.txt_IdGuncelleme.setText("");
        this.txt_malzemeAdiGuncelleme.setText("");
        this.txt_MalzemeStokGuncelleme.setText("");
        this.txt_MalzemeSktGuncelleme.setDate(null);
        this.txt_MalzemeTedarikciGuncelleme.setText("");
        this.txtArea_MalzemeAciklamasiGuncelleme.setText("");
    }

    private boolean isValidId(int idText) {
        String regex = "^[1-9]\\d*$"; // 0'dan farklı pozitif tam sayılar
        String idString = String.valueOf(idText);
        return idString.matches(regex);
    }

// Malzeme adı için geçerlilik kontrolü
    private boolean isValidMalzemeAdi(String malzemeAdi) {
        String regex = "^[A-Za-zÇçĞğİıÖöŞşÜü\\s]+$"; // Türkçe karakterleri de kabul eden metin
        return malzemeAdi.matches(regex) && !malzemeAdi.trim().isEmpty();
    }


    private void jPanel2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel2FocusGained

    }//GEN-LAST:event_jPanel2FocusGained

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
        updateTable();
    }//GEN-LAST:event_formFocusGained

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        updateTable();
    }//GEN-LAST:event_formWindowOpened

    private void btn_GuncelleTaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GuncelleTaraActionPerformed
        // TODO add your handling code here:
        String search = txt_GuncelleTara.getText();
        DefaultTableModel model = (DefaultTableModel) tbl_Guncelle.getModel();
        ArrayList<Ali_Yilmaz_2121221031_bp2_p2_Malzemeler> mlist = Ali_Yilmaz_2121221031_bp2_p2_MalzemeDB.searchByNameOrId(search);
        model.setRowCount(0);
        for (Ali_Yilmaz_2121221031_bp2_p2_Malzemeler nm1 : mlist) {
            model.addRow(new Object[]{nm1.id, nm1.malzeme_adi, nm1.malzeme_kategorisi, nm1.malzeme_Stok, nm1.malzeme_skt, nm1.malzeme_tedarikci, nm1.malzeme_aciklama});
        }
    }//GEN-LAST:event_btn_GuncelleTaraActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        Ali_Yilmaz_2121221031_bp2_p2_Main main = new Ali_Yilmaz_2121221031_bp2_p2_Main();
        main.setVisible(true);

    }//GEN-LAST:event_formWindowClosed
    private void updateTable() {
        DefaultTableModel model = (DefaultTableModel) tbl_Guncelle.getModel();
        model.setRowCount(0); // Tabloyu temizle

        // Veritabanından verileri çekme işlemleri
        ArrayList<Ali_Yilmaz_2121221031_bp2_p2_Malzemeler> malzemeler = Ali_Yilmaz_2121221031_bp2_p2_MalzemeDB.getMaterials();

        // Verileri tabloya ekleme
        for (Ali_Yilmaz_2121221031_bp2_p2_Malzemeler malzeme : malzemeler) {
            Object[] row = {malzeme.id, malzeme.malzeme_adi, malzeme.malzeme_kategorisi, malzeme.malzeme_Stok, malzeme.malzeme_skt, malzeme.malzeme_tedarikci, malzeme.malzeme_aciklama};
            model.addRow(row);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ali_Yilmaz_2121221031_bp2_p2_MalzemeAraGuncelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ali_Yilmaz_2121221031_bp2_p2_MalzemeAraGuncelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ali_Yilmaz_2121221031_bp2_p2_MalzemeAraGuncelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ali_Yilmaz_2121221031_bp2_p2_MalzemeAraGuncelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ali_Yilmaz_2121221031_bp2_p2_MalzemeAraGuncelle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Guncelle;
    private javax.swing.JButton btn_GuncelleTara;
    private javax.swing.JComboBox<String> cmb_MalzemeKategorisiGuncelleme;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_Guncelle;
    private javax.swing.JTextArea txtArea_MalzemeAciklamasiGuncelleme;
    private javax.swing.JTextField txt_GuncelleTara;
    private javax.swing.JTextField txt_IdGuncelleme;
    private com.toedter.calendar.JDateChooser txt_MalzemeSktGuncelleme;
    private javax.swing.JTextField txt_MalzemeStokGuncelleme;
    private javax.swing.JTextField txt_MalzemeTedarikciGuncelleme;
    private javax.swing.JTextField txt_malzemeAdiGuncelleme;
    // End of variables declaration//GEN-END:variables
}
