/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BpProject2;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author fbali
 */
public class Ali_Yilmaz_2121221031_bp2_p2_KayitOl extends javax.swing.JFrame {

    /**
     * Creates new form KayitOl
     */
    public Ali_Yilmaz_2121221031_bp2_p2_KayitOl() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_name_surname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_UserId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        radio_Admin = new javax.swing.JRadioButton();
        radio_User = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btn_Kayit = new javax.swing.JButton();
        txt_password = new javax.swing.JPasswordField();
        btn_SifreyiGoster = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jPanel2.setBackground(new java.awt.Color(112, 191, 244));

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 106, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("sansserif", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Ad Soyad");

        jLabel2.setFont(new java.awt.Font("sansserif", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Kullanıcı Adı");

        jLabel3.setFont(new java.awt.Font("sansserif", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Şifre");

        buttonGroup1.add(radio_Admin);
        radio_Admin.setFont(new java.awt.Font("sansserif", 3, 14)); // NOI18N
        radio_Admin.setForeground(new java.awt.Color(0, 0, 0));
        radio_Admin.setText("Admin");

        buttonGroup1.add(radio_User);
        radio_User.setFont(new java.awt.Font("sansserif", 3, 14)); // NOI18N
        radio_User.setForeground(new java.awt.Color(0, 0, 0));
        radio_User.setText("User");

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\fbali\\Downloads\\signup (2).png")); // NOI18N

        jButton1.setBackground(new java.awt.Color(0, 204, 255));
        jButton1.setFont(new java.awt.Font("sansserif", 3, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Giriş Ekranı");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("sansserif", 3, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Eğer hesabınız varsa");

        btn_Kayit.setBackground(new java.awt.Color(0, 204, 255));
        btn_Kayit.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btn_Kayit.setForeground(new java.awt.Color(0, 0, 0));
        btn_Kayit.setText("Kayıt Ol");
        btn_Kayit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_KayitActionPerformed(evt);
            }
        });

        btn_SifreyiGoster.setBackground(new java.awt.Color(0, 204, 255));
        btn_SifreyiGoster.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btn_SifreyiGoster.setForeground(new java.awt.Color(0, 0, 0));
        btn_SifreyiGoster.setText("Şifreyi Göster");
        btn_SifreyiGoster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SifreyiGosterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 232, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(radio_Admin))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_UserId)
                                    .addComponent(txt_name_surname, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                    .addComponent(txt_password))
                                .addGap(33, 33, 33)
                                .addComponent(btn_SifreyiGoster)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(radio_User)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(btn_Kayit)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel6)))
                                .addGap(58, 58, 58))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radio_User)
                            .addComponent(radio_Admin))
                        .addGap(31, 31, 31))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_name_surname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_UserId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_SifreyiGoster))
                        .addGap(54, 54, 54)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Kayit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(76, 76, 76))
        );

        jPanel1.add(jPanel2);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Ali_Yilmaz_2121221031_bp2_p2_GirisEkrani giris = new Ali_Yilmaz_2121221031_bp2_p2_GirisEkrani();
        giris.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_KayitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_KayitActionPerformed
       try {
        Ali_Yilmaz_2121221031_bp2_p2_Users users = new Ali_Yilmaz_2121221031_bp2_p2_Users();
        users.name_surname = txt_name_surname.getText();
        users.User_Id = txt_UserId.getText();
        users.password = txt_password.getText();

        if (radio_Admin.isSelected()) {
            users.Position = radio_Admin.getText();
        } else if (radio_User.isSelected()) {
            users.Position = radio_User.getText();
        } else {
            throw new Exception("Admin veya User olma durumu seçilmeli !");
        }

        validateNameSurname(txt_name_surname.getText());
        validateUserId(txt_UserId.getText());
        validatePassword(txt_password.getText());

        if (Ali_Yilmaz_2121221031_bp2_p2_MalzemeDB.AddUser(users)) {
            JOptionPane.showMessageDialog(this, "Kullanıcı Veri Tabanına Eklendi");
            TabloSifirlama();
        } else {
            JOptionPane.showMessageDialog(this, "Veri Tabanına Ekleme Başarısız");
        }
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, ex.getMessage());
    }

    }//GEN-LAST:event_btn_KayitActionPerformed

    private void btn_SifreyiGosterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SifreyiGosterActionPerformed
    // TODO add your handling code here:
    if (txt_password.getEchoChar() == '\u2022') {
        txt_password.setEchoChar((char) 0); // Show the password as plain text
    } else {
        txt_password.setEchoChar('\u2022'); // Show the password as masked text (bullet character)
    }
    }//GEN-LAST:event_btn_SifreyiGosterActionPerformed

    public void TabloSifirlama() {
        txt_name_surname.setText("");
        txt_UserId.setText("");
        txt_password.setText("");
        buttonGroup1.clearSelection();

    }

    public void validateNameSurname(String nameSurname) {
        String regex = "^[A-Za-z\\s]+$";
        if (!nameSurname.matches(regex)) {
            throw new IllegalArgumentException("Geçersiz isim/soyisim formatı");
        }
    }

    public void validateUserId(String userId) {
        String regex = "^[a-zA-Z0-9]+$";
        if (!userId.matches(regex)) {
            throw new IllegalArgumentException("Geçersiz kullanıcı ID formatı");
        }
    }

    public void validatePassword(String password) {
    String regex = "^[A-Za-z\\d]{5,20}$";


if (!password.matches(regex)) {
    throw new IllegalArgumentException("Geçersiz şifre formatı");
}

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ali_Yilmaz_2121221031_bp2_p2_KayitOl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ali_Yilmaz_2121221031_bp2_p2_KayitOl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ali_Yilmaz_2121221031_bp2_p2_KayitOl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ali_Yilmaz_2121221031_bp2_p2_KayitOl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ali_Yilmaz_2121221031_bp2_p2_KayitOl().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Kayit;
    private javax.swing.JButton btn_SifreyiGoster;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton radio_Admin;
    private javax.swing.JRadioButton radio_User;
    private javax.swing.JTextField txt_UserId;
    private javax.swing.JTextField txt_name_surname;
    private javax.swing.JPasswordField txt_password;
    // End of variables declaration//GEN-END:variables
}
