/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BpProject2;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fbali
 */
public class Ali_Yilmaz_2121221031_bp2_p2_UrunTalebiOlustur extends javax.swing.JFrame {

    /**
     * Creates new form UrunTalebiOlustur
     */
    public Ali_Yilmaz_2121221031_bp2_p2_UrunTalebiOlustur() {
        initComponents();
        this.setTitle("Urun Talebi Oluşturma");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btn_TalepAra = new javax.swing.JButton();
        txt_TalepAra = new javax.swing.JTextField();
        btn_AnaMenü = new javax.swing.JButton();
        btn_TalepSil = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btn_TalepGuncelle = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_MalzemeTalebi = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_TalepGerekcesi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_TalepMiktarı = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        combo_TalepOnceliği = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        combo_TalepKategorisi = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        btn_TalepEkle = new javax.swing.JButton();
        txt_TalepTarihi = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Talep = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1326, 700));
        setMinimumSize(new java.awt.Dimension(1326, 700));
        setPreferredSize(new java.awt.Dimension(1326, 700));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        btn_TalepAra.setText("Talep Ara");
        btn_TalepAra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TalepAraActionPerformed(evt);
            }
        });

        btn_AnaMenü.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btn_AnaMenü.setText("<-- Ana Menüye Dön");
        btn_AnaMenü.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AnaMenüActionPerformed(evt);
            }
        });

        btn_TalepSil.setText("Talep Sil");
        btn_TalepSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TalepSilActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("                                                                                                                                                                     MALZEME TALEP OLUŞTURMA EKRANINA HOŞGELDİNİZ");

        btn_TalepGuncelle.setText("Talep Güncelle");
        btn_TalepGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TalepGuncelleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btn_AnaMenü)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 483, Short.MAX_VALUE)
                .addComponent(btn_TalepGuncelle)
                .addGap(18, 18, 18)
                .addComponent(btn_TalepAra, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_TalepAra, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_TalepSil, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(208, 208, 208))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 1293, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_TalepAra)
                    .addComponent(txt_TalepAra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_AnaMenü)
                    .addComponent(btn_TalepSil)
                    .addComponent(btn_TalepGuncelle))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Talep Oluşturma ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 12))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Malzeme Talebi");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Talep Önceliği");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Talep Miktarı");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Talep Tarihi");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Talep Kategorisi");

        combo_TalepOnceliği.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Düşük ", "Orta", "Yüksek" }));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Talep Gerekçesi");

        combo_TalepKategorisi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kimyasallar", "Cam Eşyalar", "Metal Eşyalar", "Plastik Eşyalar", "Ölçüm Cihazları", "Biyolojik Malzemeler", "Elektrikli Malzemeler", "Optik Malzemeler" }));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\fbali\\Downloads\\quote-request.png")); // NOI18N

        btn_TalepEkle.setText("Talebi Ekle");
        btn_TalepEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TalepEkleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1))
                        .addGap(104, 104, 104)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(combo_TalepKategorisi, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_MalzemeTalebi, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(combo_TalepOnceliği, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_TalepMiktarı, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_TalepGerekcesi)
                            .addComponent(txt_TalepTarihi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_TalepEkle)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_MalzemeTalebi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(combo_TalepOnceliği, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txt_TalepMiktarı, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txt_TalepTarihi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(combo_TalepKategorisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txt_TalepGerekcesi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(btn_TalepEkle)
                .addGap(57, 57, 57))
        );

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));

        tbl_Talep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Talep Id", "Malzeme Talebi", "Talep Önceliği", "Talep Miktarı", "Talep Tarihi", "Talep Kategorisi", "Talep Açıklaması"
            }
        ));
        jScrollPane1.setViewportView(tbl_Talep);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 777, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // JDateChooser'dan tarihi alın

    private void btn_TalepEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TalepEkleActionPerformed
        try {
            Ali_Yilmaz_2121221031_bp2_p2_TalepOlusturma talep = new Ali_Yilmaz_2121221031_bp2_p2_TalepOlusturma();
            talep.MalzemeTalebi = txt_MalzemeTalebi.getText();
            talep.TalepOnceligi = combo_TalepOnceliği.getSelectedItem().toString();
            talep.TalepMiktarı = txt_TalepMiktarı.getText();
            java.util.Date selectedDate = txt_TalepTarihi.getDate();

            if (selectedDate != null) {
                // Tarih formatını belirleyin
                java.text.SimpleDateFormat dateFormat = new java.text.SimpleDateFormat("dd/MM/yyyy");

// Seçilen tarihi istediğiniz formatta bir metin olarak alın
                String formattedDate = dateFormat.format(selectedDate);

// Elde edilen metni kullanabilirsiniz
                talep.TalepTarihi = formattedDate;
            } else {

                talep.TalepTarihi = ""; // veya talep.TalepTarihi = null;
                JOptionPane.showMessageDialog(this, "Geçerli bir tarih seçiniz.", "Hata", JOptionPane.ERROR_MESSAGE);
            }

            talep.TalepKategorisi = combo_TalepKategorisi.getSelectedItem().toString();
            talep.TalepGerekcesi = txt_TalepGerekcesi.getText();

            if (talep.MalzemeTalebi.isEmpty()) {
                throw new IllegalArgumentException("Malzeme Talebi alanı boş olamaz");
            }

            if (talep.TalepMiktarı.isEmpty()) {
                throw new IllegalArgumentException("Talep Miktarı alanı boş olamaz");
            }

            if (selectedDate != null) {
            } else {
                throw new IllegalArgumentException("Talep Tarihi alanı boş olamaz");
            }

            if (talep.TalepGerekcesi.isEmpty()) {
                throw new IllegalArgumentException("Talep Gerekçesi alanı boş olamaz");
            }

            if (Ali_Yilmaz_2121221031_bp2_p2_MalzemeDB.AddRequest(talep)) {
                JOptionPane.showMessageDialog(this, "Talepler Veri Tabanına Eklendi");
                TabloSifirlama();
            } else {
                JOptionPane.showMessageDialog(this, "Veri Tabanına Ekleme Başarısız");
            }
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }


    }//GEN-LAST:event_btn_TalepEkleActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        updateTable();

    }//GEN-LAST:event_formWindowOpened

    private void btn_AnaMenüActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AnaMenüActionPerformed
        // TODO add your handling code here:
        Ali_Yilmaz_2121221031_bp2_p2_Main main = new Ali_Yilmaz_2121221031_bp2_p2_Main();
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_AnaMenüActionPerformed

    private void btn_TalepSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TalepSilActionPerformed
        // TODO add your handling code here:
        String kullaniciAdi = Ali_Yilmaz_2121221031_bp2_p2_GirisEkrani.UserId;
        String sifre = Ali_Yilmaz_2121221031_bp2_p2_GirisEkrani.Password;
        String position = Ali_Yilmaz_2121221031_bp2_p2_MalzemeDB.getUserPosition(kullaniciAdi, sifre);

        if (position != null) {
            // Kullanıcı doğrulandı, işleme devam et
            if (position.equals("Admin")) {
                int choice = JOptionPane.showConfirmDialog(this, "Gerçekten silmek istiyor musunuz? Bu işlem geri alınamaz.", "Malzeme Silme", JOptionPane.YES_NO_OPTION);
                if (choice == JOptionPane.YES_OPTION) {
                    int selectedRow = tbl_Talep.getSelectedRow();

                    // Satırın verilerini al
                    int id = Integer.parseInt(tbl_Talep.getValueAt(selectedRow, 0).toString());
                    // Diğer verileri de ihtiyaca göre al

                    // Veriyi sil
                    boolean isDeleted = Ali_Yilmaz_2121221031_bp2_p2_MalzemeDB.DeleteRequestById(id);
                    if (isDeleted) {
                        // Veri silme işlemi başarılıysa
                        JOptionPane.showMessageDialog(this, "Veri başarıyla silindi.");

                        // Tabloyu güncelle
                        updateTable();
                    } else {
                        // Veri silme işlemi başarısızsa
                        JOptionPane.showMessageDialog(this, "Veri silme işlemi başarısız.");
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Silmek için Admin olmanız gerekli", "Silme işlemi", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Kullanıcı adı veya şifre hatalı", "Hatalı Giriş", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_TalepSilActionPerformed

    private void btn_TalepAraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TalepAraActionPerformed
        String search = txt_TalepAra.getText(); // Arama kriterini metin alanından alın
        DefaultTableModel model = (DefaultTableModel) tbl_Talep.getModel(); // Tablo modelini alın
        ArrayList<Ali_Yilmaz_2121221031_bp2_p2_TalepOlusturma> talepListesi = Ali_Yilmaz_2121221031_bp2_p2_MalzemeDB.searchByNameOrPriority(search); // Özelliklere göre talepleri ara

        model.setRowCount(0); // Tablo modelinin satır sayısını sıfırla

        // Her bir talep için tabloya yeni bir satır ekle
        for (Ali_Yilmaz_2121221031_bp2_p2_TalepOlusturma talep : talepListesi) {
            model.addRow(new Object[]{talep.TalepId, talep.MalzemeTalebi, talep.TalepOnceligi, talep.TalepMiktarı, talep.TalepTarihi, talep.TalepKategorisi, talep.TalepGerekcesi});
        }

    }//GEN-LAST:event_btn_TalepAraActionPerformed

    private void btn_TalepGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TalepGuncelleActionPerformed
        //SIKINTI VAR BAK BURAYA SONRA
        int selectedRowIndex = tbl_Talep.getSelectedRow();

        // Seçilen bir satır varsa devam edin
        if (selectedRowIndex != -1) {
            Ali_Yilmaz_2121221031_bp2_p2_TalepOlusturma existingRequest = new Ali_Yilmaz_2121221031_bp2_p2_TalepOlusturma();

            try {
                // Seçilen satırdaki TalepId değerini alın
                int talepId = (int) tbl_Talep.getValueAt(selectedRowIndex, 0);

                // Tablodan ilgili talebi alın
                existingRequest = Ali_Yilmaz_2121221031_bp2_p2_MalzemeDB.getRequestById(talepId);

                if (existingRequest == null) {
                    throw new IllegalArgumentException("Güncelleme yapılacak talep bulunamadı");
                }

                // Güncelleme yapılacak talep bilgilerini alın
                String malzemeTalebi = txt_MalzemeTalebi.getText();
                String TalepOnceligi = combo_TalepOnceliği.getSelectedItem().toString();
                String talepMiktari = txt_TalepMiktarı.getText();
                java.util.Date selectedDate = txt_TalepTarihi.getDate();

// Tarih formatını belirleyin
                java.text.SimpleDateFormat dateFormat = new java.text.SimpleDateFormat("dd/MM/yyyy");

// Seçilen tarihi istediğiniz formatta bir metin olarak alın
                String formattedDate = dateFormat.format(selectedDate);

                String TalepKategorisi = combo_TalepKategorisi.getSelectedItem().toString();
                String talepGerekcesi = txt_TalepGerekcesi.getText();

                // Yeni talep ve öncelik değerlerini kontrol edin
                if (malzemeTalebi.isEmpty()) {
                    throw new IllegalArgumentException("Malzeme Talebi alanı boş bırakılamaz");
                }

                if (talepMiktari.isEmpty()) {
                    throw new IllegalArgumentException("Talep Miktarı alanı boş bırakılamaz");
                }
                if (selectedDate == null) {
                    throw new IllegalArgumentException("Talep Tarihi alanı boş bırakılamaz");
                }

                if (talepGerekcesi.isEmpty()) {
                    throw new IllegalArgumentException("Talep Gerekçesi alanı boş bırakılamaz");
                }

                // Talep bilgilerini güncelle
                //existingRequest.setTalepId(talepId);
                existingRequest.setMalzemeTalebi(malzemeTalebi);
                existingRequest.setTalepOnceligi(TalepOnceligi);
                existingRequest.setTalepMiktarı(talepMiktari);

                existingRequest.setTalepTarihi(formattedDate);
                existingRequest.setTalepKategorisi(TalepKategorisi);
                existingRequest.setTalepGerekcesi(talepGerekcesi);

                // Talebi güncelle
                boolean isSuccess = Ali_Yilmaz_2121221031_bp2_p2_MalzemeDB.UpdateRequest(existingRequest);

                if (isSuccess) {
                    JOptionPane.showMessageDialog(this, "Talep başarıyla güncellendi.", "Bilgi", JOptionPane.INFORMATION_MESSAGE);
                    // Tabloyu güncelle
                    TabloSifirlama();
                } else {
                    JOptionPane.showMessageDialog(this, "Talep güncellenirken bir hata oluştu.", "Hata", JOptionPane.ERROR_MESSAGE);
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Geçersiz Talep ID formatı");
            } catch (IllegalArgumentException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Tablodan güncellenecek bir talep seçin!");
        }
    }//GEN-LAST:event_btn_TalepGuncelleActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        Ali_Yilmaz_2121221031_bp2_p2_Main main = new Ali_Yilmaz_2121221031_bp2_p2_Main();
        main.setVisible(true);
    }//GEN-LAST:event_formWindowClosed
    private void TabloSifirlama() {

        this.txt_MalzemeTalebi.setText("");
        this.txt_TalepGerekcesi.setText("");
        this.txt_TalepTarihi.setDate(null);
        this.txt_TalepMiktarı.setText("");
        this.combo_TalepKategorisi.setSelectedIndex(0);
        this.combo_TalepOnceliği.setSelectedIndex(0);

    }

    private void updateTable() {
        DefaultTableModel model = (DefaultTableModel) tbl_Talep.getModel();
        model.setRowCount(0); // Tabloyu temizle

        // Veritabanından talepleri çekme işlemi
        ArrayList<Ali_Yilmaz_2121221031_bp2_p2_TalepOlusturma> talepler = Ali_Yilmaz_2121221031_bp2_p2_MalzemeDB.pullRequest();

        // Talepleri tabloya ekleme
        for (Ali_Yilmaz_2121221031_bp2_p2_TalepOlusturma talep : talepler) {
            Object[] row = {talep.TalepId, talep.MalzemeTalebi, talep.TalepOnceligi, talep.TalepMiktarı, talep.TalepTarihi, talep.TalepKategorisi, talep.TalepGerekcesi};
            model.addRow(row);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ali_Yilmaz_2121221031_bp2_p2_UrunTalebiOlustur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ali_Yilmaz_2121221031_bp2_p2_UrunTalebiOlustur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ali_Yilmaz_2121221031_bp2_p2_UrunTalebiOlustur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ali_Yilmaz_2121221031_bp2_p2_UrunTalebiOlustur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ali_Yilmaz_2121221031_bp2_p2_UrunTalebiOlustur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_AnaMenü;
    private javax.swing.JButton btn_TalepAra;
    private javax.swing.JButton btn_TalepEkle;
    private javax.swing.JButton btn_TalepGuncelle;
    private javax.swing.JButton btn_TalepSil;
    private javax.swing.JComboBox<String> combo_TalepKategorisi;
    private javax.swing.JComboBox<String> combo_TalepOnceliği;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_Talep;
    private javax.swing.JTextField txt_MalzemeTalebi;
    private javax.swing.JTextField txt_TalepAra;
    private javax.swing.JTextField txt_TalepGerekcesi;
    private javax.swing.JTextField txt_TalepMiktarı;
    private com.toedter.calendar.JDateChooser txt_TalepTarihi;
    // End of variables declaration//GEN-END:variables
}
